### ISSUE TITLE
Feedback Teste TDD e BDD - Iteração 1

### ISSUE THREAD

**Issue by mateusc42** [BrunoMota18/PROJETO-IF977#26]
Iae pessoal, vou dar o feedback dos testes TDD e BDD da iteração 1 de vocês. :)

## Testes TDD:
<ul>
  <li>Não encontrei a implementação dos testes TDD para o período da iteração 1</li>
</ul>

### Nota Final: 0
---------------------------------------------------------------

## Testes BDD:
<ul>
  <li>Não encontrei a implementação dos testes BDD para o período da iteração 1</li>
</ul>

### Nota Final: 0
---------------------------------------------------------------

## Nota Final Total: 0

**Comment by VitorCardim** [comment]
Realmente não tinhamos os TDDs, os BDDs tinhamos as histórias em connextra e features, mas sem os steps, dá pra reaproveitar algo?
