### ISSUE TITLE
Feedback Postmortem IT3

### ISSUE THREAD

**Issue by joismar** [BrunoMota18/PROJETO-IF977#41]
Opa! Para esse item foram avaliados os seguintes critérios:

- Período: **Ok**
- O que estava planejado: **Ok**
- O que foi feito: **Ok**
- O que não foi feito: **Ok**
- O que está planejado pra próxima iteração: **Ok**
- Lições aprendidas: **Ok**

Nota Final: **10**

Qualquer dúvida estou a disposição no Telegram. ;)

**Comment by VitorCardim** [comment]
Obrigado pela atenção
