### ISSUE TITLE
FeedBack IT01 -  Postmortem 

### ISSUE THREAD

**Issue by Lerissonf** [BrunoMota18/PROJETO-IF977#42]
## Boa noite pessoal desculpem a demora para a correção dessa interação, mas segue aí a avaliação.
<h3><ul>
  <li>Período: Ok</li>
  <li>O que estava planejado: Ok</li>
  <li>O que estava planejado: Ok</li>
  <li>O que foi feito: Ok</li>
  <li>O que não foi feito: Ok</li>
  <li>O que está planejado pra próxima iteração: Ok</li>
  <li>Lições aprendidas: Ok</li>
</ul></h3>

## Nota Final: 10,00

**Comment by VitorCardim** [comment]
vlw
